default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password:
  host: <%= ENV.fetch('DB_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT_5432_TCP_PORT', '5432') %>

development:
  <<: *default
  database: seshook_development

test:
  <<: *default
  database: seshook_test

staging:
  <<: *default
  database: seshook_staging
  password: <%= ENV.fetch('DB_ENV_POSTGRES_PASSWORD', '') %>

production:
  <<: *default
  database: seshook_production
  password: <%= ENV.fetch('DB_ENV_POSTGRES_PASSWORD', '') %>
