# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e8450de42760bc35ba584804fa68669f2cea4638a3007a7aa837ad7f173c2c87e6b513eb6c60593aba75f6359a976dc8fdf9443aa29d95bff12f609412a8d27

test:
  secret_key_base: 412f6c79c3a4319916ffdb0d71be09663e3c3436eda27794ef8dab01bbbcb372c26abd7f96546e280401095d0f162e4aa3d07028342e3bcea282f9f2e8ffaae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
