db:
  image: mdillon/postgis
  environment:
    - POSTGRES_PASSWORD=st7Senup
  ports:
    - "5432:5432"

redis:
  image: redis
  ports:
    - "6379:6379"

elasticsearch:
  image: elasticsearch
  ports:
    - "9300:9300"

worker:
  image: seshook-worker
  links:
    - db
    - redis
    - elasticsearch

web:
  image: seshook-app
  ports:
    - "80:80"
  links:
    - db
    - redis
    - elasticsearch
