db:
  image: mdillon/postgis
  environment:
    - POSTGRES_PASSWORD=st7Senup
  ports:
    - "5432:5432"

redis:
  image: redis
  ports:
    - "6379:6379"

worker:
  image: seshook-worker
  links:
    - db
    - redis

web:
  image: seshook-app
  environment:
    - RAILS_ENV=staging
    - PASSENGER_APP_ENV=staging
  ports:
    - "80:80"
  links:
    - db
    - redis
